CREATE TABLE dbo.Products (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Name NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Price DECIMAL(18,2) NOT NULL CHECK (Price > 0),
    Stock INT NOT NULL CHECK (Stock >= 0),
    CreateDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdateDate DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
